/* Auto-generated from mesg_J. Do not edit manually. */
#ifndef MESG_J_H
#define MESG_J_H

extern char mesg[507][256];

static inline void init_embedded_mesg(void) {
    mesg[0][0] = '\0';
    snprintf(mesg[1], sizeof(mesg[1]), "%s", "Message Japanese version (by ohta@src.ricoh.co.jp)");
    snprintf(mesg[2], sizeof(mesg[2]), "%s", "食糧");
    snprintf(mesg[3], sizeof(mesg[3]), "%s", "巻き物");
    snprintf(mesg[4], sizeof(mesg[4]), "%s", "水薬");
    snprintf(mesg[5], sizeof(mesg[5]), "%s", "つえ");
    mesg[6][0] = '\0';
    snprintf(mesg[7], sizeof(mesg[7]), "%s", "よろい");
    snprintf(mesg[8], sizeof(mesg[8]), "%s", "指輪");
    snprintf(mesg[9], sizeof(mesg[9]), "%s", "魔除け");
    snprintf(mesg[10], sizeof(mesg[10]), "%s", "やあ、%s。 運命の洞窟へようこそ...");
    snprintf(mesg[11], sizeof(mesg[11]), "%s", "［続く］");
    snprintf(mesg[12], sizeof(mesg[12]), "%s", "それでは、またね。");
    snprintf(mesg[13], sizeof(mesg[13]), "%s", "おたく、いったい誰なの？");
    snprintf(mesg[14], sizeof(mesg[14]), "%s", "ごめん！ 画面の大きさは最低２４×８０なんだ。");
    snprintf(mesg[15], sizeof(mesg[15]), "%s", "割り込みがあった。");
    snprintf(mesg[16], sizeof(mesg[16]), "%s", "好きな果物");
    snprintf(mesg[17], sizeof(mesg[17]), "%s", "メモリーが足りません。 ゲームを終了します。");
    snprintf(mesg[18], sizeof(mesg[18]), "%s", "%sの攻撃はそれた。 ");
    snprintf(mesg[19], sizeof(mesg[19]), "%s", "%s%sは命中した。 ");
    mesg[20][0] = '\0';
    snprintf(mesg[21], sizeof(mesg[21]), "%s", "の攻撃");
    snprintf(mesg[22], sizeof(mesg[22]), "%s", "%sの攻撃はそれた。 ");
    snprintf(mesg[23], sizeof(mesg[23]), "%s", "%sの攻撃は命中した。 ");
    snprintf(mesg[24], sizeof(mesg[24]), "%s", "%sを倒した。 ");
    snprintf(mesg[25], sizeof(mesg[25]), "%s", "その方向には怪物がいない。");
    snprintf(mesg[26], sizeof(mesg[26]), "%s", "持ちものは、１つも持っていない。");
    snprintf(mesg[27], sizeof(mesg[27]), "%s", "イェンダーの魔除け");
    snprintf(mesg[28], sizeof(mesg[28]), "%s", "個の金塊");
    snprintf(mesg[29], sizeof(mesg[29]), "%s", "本の");
    snprintf(mesg[30], sizeof(mesg[30]), "%s", "袋の");
    snprintf(mesg[31], sizeof(mesg[31]), "%s", "個の");
    snprintf(mesg[32], sizeof(mesg[32]), "%s", "つの");
    snprintf(mesg[33], sizeof(mesg[33]), "%s", "という");
    snprintf(mesg[34], sizeof(mesg[34]), "%s", "と呼ぶ");
    snprintf(mesg[35], sizeof(mesg[35]), "%s", "（使っている）");
    snprintf(mesg[36], sizeof(mesg[36]), "%s", "（着ている）");
    snprintf(mesg[37], sizeof(mesg[37]), "%s", "（左手）");
    snprintf(mesg[38], sizeof(mesg[38]), "%s", "（右手）");
    snprintf(mesg[39], sizeof(mesg[39]), "%s", "の");
    snprintf(mesg[40], sizeof(mesg[40]), "%s", "の");
    snprintf(mesg[41], sizeof(mesg[41]), "%s", "調べる持ちものの種類は？");
    snprintf(mesg[42], sizeof(mesg[42]), "%s", "それは持っていない。");
    snprintf(mesg[43], sizeof(mesg[43]), "%s", "武器は使っていない。");
    snprintf(mesg[44], sizeof(mesg[44]), "%s", "よろいは着ていない。");
    snprintf(mesg[45], sizeof(mesg[45]), "%s", "どの種類のものですか？");
    snprintf(mesg[46], sizeof(mesg[46]), "%s", "知っているものは、何もない。");
    snprintf(mesg[47], sizeof(mesg[47]), "%s", "  （知っている%sはない）");
    snprintf(mesg[48], sizeof(mesg[48]), "%s", "降りられない！");
    snprintf(mesg[49], sizeof(mesg[49]), "%s", "降りる階段がない。");
    snprintf(mesg[50], sizeof(mesg[50]), "%s", "登る階段がない。");
    snprintf(mesg[51], sizeof(mesg[51]), "%s", "階段は何者かの手によってふさがれている。");
    snprintf(mesg[52], sizeof(mesg[52]), "%s", "胃袋をねじ切られるような気分がした。");
    snprintf(mesg[53], sizeof(mesg[53]), "%s", "レベル%sへようこそ。");
    snprintf(mesg[54], sizeof(mesg[54]), "%s", "基本上昇率: %d.%02d, 実効上昇率: %d.%02d (!: %d, V: %d)");
    snprintf(mesg[55], sizeof(mesg[55]), "%s", "方角は？");
    snprintf(mesg[56], sizeof(mesg[56]), "%s", "階: ");
    snprintf(mesg[57], sizeof(mesg[57]), "%s", "金塊: ");
    snprintf(mesg[58], sizeof(mesg[58]), "%s", "体力: ");
    snprintf(mesg[59], sizeof(mesg[59]), "%s", "強さ: ");
    snprintf(mesg[60], sizeof(mesg[60]), "%s", "守備: ");
    snprintf(mesg[61], sizeof(mesg[61]), "%s", "経験: ");
    snprintf(mesg[62], sizeof(mesg[62]), "%s", "階:    金塊:        体力:          強さ:        守備:    経験:                ");
    snprintf(mesg[63], sizeof(mesg[63]), "%s", "何者か");
    snprintf(mesg[64], sizeof(mesg[64]), "%s", "遠くから、かすかな怒りの叫びが聞こえる。");
    snprintf(mesg[65], sizeof(mesg[65]), "%s", "どこからか、かん高いうなり声が聞こえてくる。");
    snprintf(mesg[66], sizeof(mesg[66]), "%s", "ようやく体が自由になった。");
    snprintf(mesg[67], sizeof(mesg[67]), "%s", "怪物につかまえられて、逃げられない。");
    snprintf(mesg[68], sizeof(mesg[68]), "%s", "熊のわなが、なかなかはずれない。");
    snprintf(mesg[69], sizeof(mesg[69]), "%s", "を手に入れた。");
    snprintf(mesg[70], sizeof(mesg[70]), "%s", "の上にいる。");
    snprintf(mesg[71], sizeof(mesg[71]), "%s", "空腹");
    snprintf(mesg[72], sizeof(mesg[72]), "%s", "空腹になってきた。");
    snprintf(mesg[73], sizeof(mesg[73]), "%s", "飢餓");
    snprintf(mesg[74], sizeof(mesg[74]), "%s", "空腹のせいで力がなくなってきた。");
    snprintf(mesg[75], sizeof(mesg[75]), "%s", "瀕死");
    snprintf(mesg[76], sizeof(mesg[76]), "%s", "空腹で、もう死にそうだ。");
    snprintf(mesg[77], sizeof(mesg[77]), "%s", "空腹で、目がくらくらする。");
    snprintf(mesg[78], sizeof(mesg[78]), "%s", "ようやく地面に足がついた。");
    snprintf(mesg[79], sizeof(mesg[79]), "%s", "素早くなる薬の効き目がなくなった。");
    snprintf(mesg[80], sizeof(mesg[80]), "%s", "？？？");
    snprintf(mesg[81], sizeof(mesg[81]), "%s", "これ以上は物を持てない。");
    snprintf(mesg[82], sizeof(mesg[82]), "%s", "どんなものですか？");
    snprintf(mesg[83], sizeof(mesg[83]), "%s", "%sの種類は？");
    snprintf(mesg[84], sizeof(mesg[84]), "%s", "武器");
    snprintf(mesg[85], sizeof(mesg[85]), "%s", "呪われているので、それはできない！");
    snprintf(mesg[86], sizeof(mesg[86]), "%s", "拾いあげたとたん、巻き物はちりになってしまった。");
    snprintf(mesg[87], sizeof(mesg[87]), "%s", "もうこれ以上、物は持てない。");
    snprintf(mesg[88], sizeof(mesg[88]), "%s", "そこには、すでに何かが置かれている。");
    snprintf(mesg[89], sizeof(mesg[89]), "%s", "落とす物を持っていない。");
    snprintf(mesg[90], sizeof(mesg[90]), "%s", "落とす物は？");
    snprintf(mesg[91], sizeof(mesg[91]), "%s", "それは持っていない。");
    snprintf(mesg[92], sizeof(mesg[92]), "%s", "を落とした。");
    snprintf(mesg[93], sizeof(mesg[93]), "%s", "それは１つも持っていない。");
    snprintf(mesg[94], sizeof(mesg[94]), "%s", "を脱いだ。");
    snprintf(mesg[95], sizeof(mesg[95]), "%s", "よろいを着ていない。");
    snprintf(mesg[96], sizeof(mesg[96]), "%s", "他のよろいを着ている。");
    snprintf(mesg[97], sizeof(mesg[97]), "%s", "どのよろいを？");
    snprintf(mesg[98], sizeof(mesg[98]), "%s", "それは持っていない。");
    snprintf(mesg[99], sizeof(mesg[99]), "%s", "それはよろいではない。");
    snprintf(mesg[100], sizeof(mesg[100]), "%s", "を身につけた。");
    snprintf(mesg[101], sizeof(mesg[101]), "%s", "どの武器を？");
    snprintf(mesg[102], sizeof(mesg[102]), "%s", "それは持っていない。");
    snprintf(mesg[103], sizeof(mesg[103]), "%s", "%sを武器にすることはできない。");
    snprintf(mesg[104], sizeof(mesg[104]), "%s", "よろい");
    snprintf(mesg[105], sizeof(mesg[105]), "%s", "指輪");
    snprintf(mesg[106], sizeof(mesg[106]), "%s", "その武器はもう使っている。");
    snprintf(mesg[107], sizeof(mesg[107]), "%s", "に持ちかえた。");
    snprintf(mesg[108], sizeof(mesg[108]), "%s", "呼び名をつけるものは？");
    snprintf(mesg[109], sizeof(mesg[109]), "%s", "それは持っていない。");
    snprintf(mesg[110], sizeof(mesg[110]), "%s", "それには呼び名をつけることができない。");
    snprintf(mesg[111], sizeof(mesg[111]), "%s", "呼び名は？");
    snprintf(mesg[112], sizeof(mesg[112]), "%s", "ここには、何もない。");
    snprintf(mesg[113], sizeof(mesg[113]), "%s", "拾うことができない！");
    snprintf(mesg[114], sizeof(mesg[114]), "%s", "を手に入れた。 ");
    snprintf(mesg[115], sizeof(mesg[115]), "%s", "コマンドが違います。");
    snprintf(mesg[116], sizeof(mesg[116]), "%s", "?  ヘルプを表示する  >   階段を降りる");
    snprintf(mesg[117], sizeof(mesg[117]), "%s", "/  画面の文字が表すものを表示 <   階段を登る");
    snprintf(mesg[118], sizeof(mesg[118]), "%s", "h, j, k, l 左、下、上、右に進む  .   その場で休む");
    snprintf(mesg[119], sizeof(mesg[119]), "%s", "y, u, b, n 左上、右上、左下、右下に進む ,   足元のものを拾う");
    snprintf(mesg[120], sizeof(mesg[120]), "%s", "<SHIFT><方角> 何かにぶつかるまで進む  s   わなや隠しとびらを探す");
    snprintf(mesg[121], sizeof(mesg[121]), "%s", "<CTRL><方角> 何かを見つけるまで進む  i   持ちものを見る");
    snprintf(mesg[122], sizeof(mesg[122]), "%s", "f<方角>  やられそうになるまで戦う I   １つの持ちものを見る");
    snprintf(mesg[123], sizeof(mesg[123]), "%s", "F<方角>  どちらかが倒れるまで戦う q   水薬を飲む");
    snprintf(mesg[124], sizeof(mesg[124]), "%s", "t<方角>  物を投げる   r   巻き物を読む");
    snprintf(mesg[125], sizeof(mesg[125]), "%s", "m<方角>  落ちているものの上に乗る e   食べ物を食べる");
    snprintf(mesg[126], sizeof(mesg[126]), "%s", "z<方角>  つえを振りかざす  w   武器を手に持つ");
    snprintf(mesg[127], sizeof(mesg[127]), "%s", "^<方角>  わなの種類を調べる  W   よろいを着る");
    snprintf(mesg[128], sizeof(mesg[128]), "%s", "<CTRL>P  最後のメッセージを再表示する T   よろいを脱ぐ");
    snprintf(mesg[129], sizeof(mesg[129]), "%s", "<CTRL>R  画面を描き直す   P   指輪をはめる");
    snprintf(mesg[130], sizeof(mesg[130]), "%s", "<CTRL>D  画面をファイルに書き出す R   指輪をはずす");
    snprintf(mesg[131], sizeof(mesg[131]), "%s", "<ESC>  コマンドを中止する  d   持ちものを落とす");
    snprintf(mesg[132], sizeof(mesg[132]), "%s", "a  直前のコマンドを繰り返す c   持ちものに呼び名を付ける");
    snprintf(mesg[133], sizeof(mesg[133]), "%s", "D  今まで何を発見したかを表示 )   現在の武器を見る");
    snprintf(mesg[134], sizeof(mesg[134]), "%s", "S  ゲームをセーブして終了する ]   現在のよろいを見る");
    snprintf(mesg[135], sizeof(mesg[135]), "%s", "Q  ゲームを中止する  =   現在の指輪を見る");
    snprintf(mesg[136], sizeof(mesg[136]), "%s", "v  バージョン情報を表示する @   プレイヤー行を描き直す");
    snprintf(mesg[137], sizeof(mesg[137]), "%s", "!  シェルコマンドを実行する o   オプションの表示・設定");
    snprintf(mesg[138], sizeof(mesg[138]), "%s", "プレイヤー");
    snprintf(mesg[139], sizeof(mesg[139]), "%s", "部屋の床");
    snprintf(mesg[140], sizeof(mesg[140]), "%s", "部屋の壁");
    snprintf(mesg[141], sizeof(mesg[141]), "%s", "部屋の壁");
    snprintf(mesg[142], sizeof(mesg[142]), "%s", "部屋のドア");
    snprintf(mesg[143], sizeof(mesg[143]), "%s", "部屋と部屋をむすぶ通路");
    snprintf(mesg[144], sizeof(mesg[144]), "%s", "隣の階への階段");
    snprintf(mesg[145], sizeof(mesg[145]), "%s", "隠されたわな");
    snprintf(mesg[146], sizeof(mesg[146]), "%s", "金塊");
    snprintf(mesg[147], sizeof(mesg[147]), "%s", "食糧");
    snprintf(mesg[148], sizeof(mesg[148]), "%s", "よろいかたびら");
    snprintf(mesg[149], sizeof(mesg[149]), "%s", "武器");
    snprintf(mesg[150], sizeof(mesg[150]), "%s", "巻き物");
    snprintf(mesg[151], sizeof(mesg[151]), "%s", "水薬");
    snprintf(mesg[152], sizeof(mesg[152]), "%s", "魔法の杖");
    snprintf(mesg[153], sizeof(mesg[153]), "%s", "魔法の指輪");
    snprintf(mesg[154], sizeof(mesg[154]), "%s", "イェンダーの魔除け");
    snprintf(mesg[155], sizeof(mesg[155]), "%s", "どんな文字ですか？");
    snprintf(mesg[156], sizeof(mesg[156]), "%s", "[ exit コマンドでローグに戻ります ]");
    snprintf(mesg[157], sizeof(mesg[157]), "%s", "[ シェルを終了するとローグに戻ります ]");
    snprintf(mesg[158], sizeof(mesg[158]), "%s", "左手(L)、それとも右手(R)？");
    snprintf(mesg[159], sizeof(mesg[159]), "%s", "そちらの手には指輪をしていない。");
    snprintf(mesg[160], sizeof(mesg[160]), "%s", "すでに両手に指輪をしている。");
    snprintf(mesg[161], sizeof(mesg[161]), "%s", "どの指輪を？");
    snprintf(mesg[162], sizeof(mesg[162]), "%s", "それは持っていない。");
    snprintf(mesg[163], sizeof(mesg[163]), "%s", "それは指輪ではない。");
    snprintf(mesg[164], sizeof(mesg[164]), "%s", "その指輪はもう手にはめている。");
    snprintf(mesg[165], sizeof(mesg[165]), "%s", "そちらの手にはもう指輪をしている。");
    snprintf(mesg[166], sizeof(mesg[166]), "%s", "をはずした。");
    snprintf(mesg[167], sizeof(mesg[167]), "%s", "指輪ははめていない。");
    snprintf(mesg[168], sizeof(mesg[168]), "%s", "寒さにより");
    snprintf(mesg[169], sizeof(mesg[169]), "%s", "飢えにより");
    snprintf(mesg[170], sizeof(mesg[170]), "%s", "毒矢により");
    snprintf(mesg[171], sizeof(mesg[171]), "%s", "逃亡により");
    snprintf(mesg[172], sizeof(mesg[172]), "%s", "死す");
    snprintf(mesg[173], sizeof(mesg[173]), "%s", "死す");
    snprintf(mesg[174], sizeof(mesg[174]), "%s", "死す");
    snprintf(mesg[175], sizeof(mesg[175]), "%s", "行方不明");
    snprintf(mesg[176], sizeof(mesg[176]), "%s", "と戦いて死す");
    snprintf(mesg[177], sizeof(mesg[177]), "%s", "安らかに");
    snprintf(mesg[178], sizeof(mesg[178]), "%s", "眠れ");
    mesg[179][0] = '\0';
    snprintf(mesg[180], sizeof(mesg[180]), "%s", "＄");
    snprintf(mesg[181], sizeof(mesg[181]), "%s", "。  所持金は＄");
    snprintf(mesg[182], sizeof(mesg[182]), "%s", "おめでとう！　君はようやく太陽の光のもとにたどりつき、");
    snprintf(mesg[183], sizeof(mesg[183]), "%s", "そして、運命の洞窟から生きて戻った勇者の一人となった。");
    snprintf(mesg[184], sizeof(mesg[184]), "%s", "君は故郷へ帰り、持ち帰った宝物を売って大金を手に入れ、");
    snprintf(mesg[185], sizeof(mesg[185]), "%s", "それからは平安に遊び暮らしたということである‥‥。　　");
    snprintf(mesg[186], sizeof(mesg[186]), "%s", "得点ファイルがオープンできません。");
    snprintf(mesg[187], sizeof(mesg[187]), "%s", "最 高 得 点");
    snprintf(mesg[188], sizeof(mesg[188]), "%s", "順位   得点    名前");
    snprintf(mesg[189], sizeof(mesg[189]), "%s", "魔除けを手に、");
    snprintf(mesg[190], sizeof(mesg[190]), "%s", "地下");
    snprintf(mesg[191], sizeof(mesg[191]), "%s", "階にて");
    snprintf(mesg[192], sizeof(mesg[192]), "%s", "寒さにより死す");
    snprintf(mesg[193], sizeof(mesg[193]), "%s", "飢えにより死す");
    snprintf(mesg[194], sizeof(mesg[194]), "%s", "毒矢により死す");
    snprintf(mesg[195], sizeof(mesg[195]), "%s", "逃亡す");
    snprintf(mesg[196], sizeof(mesg[196]), "%s", "運命の洞窟より生きて帰りたる勇者");
    snprintf(mesg[197], sizeof(mesg[197]), "%s", "と戦いて死す");
    snprintf(mesg[198], sizeof(mesg[198]), "%s", " 価格      持ちもの");
    snprintf(mesg[199], sizeof(mesg[199]), "%s", "得点ファイルが正しくありません。");
    snprintf(mesg[200], sizeof(mesg[200]), "%s", "ほのお");
    snprintf(mesg[201], sizeof(mesg[201]), "%s", "水ごけの湿り気はすぐに消え去った。");
    snprintf(mesg[202], sizeof(mesg[202]), "%s", "よろいはさびてしまった！");
    snprintf(mesg[203], sizeof(mesg[203]), "%s", "体が凍りついて、動けない！");
    snprintf(mesg[204], sizeof(mesg[204]), "%s", "金塊を盗まれた！");
    snprintf(mesg[205], sizeof(mesg[205]), "%s", "を盗まれた！");
    snprintf(mesg[206], sizeof(mesg[206]), "%s", "おっと、こいつは%sだ！");
    snprintf(mesg[207], sizeof(mesg[207]), "%s", "%sに噛まれて、毒にやられた！");
    snprintf(mesg[208], sizeof(mesg[208]), "%s", "強さが減ってしまった！");
    snprintf(mesg[209], sizeof(mesg[209]), "%s", "%sににらまれ、頭が混乱してしまった！");
    snprintf(mesg[210], sizeof(mesg[210]), "%s", "投げる武器は？");
    snprintf(mesg[211], sizeof(mesg[211]), "%s", "それは持っていない。");
    snprintf(mesg[212], sizeof(mesg[212]), "%s", "%s");
    snprintf(mesg[213], sizeof(mesg[213]), "%s", "はそれた。 ");
    snprintf(mesg[214], sizeof(mesg[214]), "%s", "は命中した。 ");
    snprintf(mesg[215], sizeof(mesg[215]), "%s", "%sは地面に落ちると、どこかに消えてしまった。");
    snprintf(mesg[216], sizeof(mesg[216]), "%s", "落し穴のわな");
    snprintf(mesg[217], sizeof(mesg[217]), "%s", "急に床がくずれ、足元から落ちてしまった！");
    snprintf(mesg[218], sizeof(mesg[218]), "%s", "熊のわな");
    snprintf(mesg[219], sizeof(mesg[219]), "%s", "熊のわなにつかまった！");
    snprintf(mesg[220], sizeof(mesg[220]), "%s", "テレポートのわな");
    snprintf(mesg[221], sizeof(mesg[221]), "%s", "テレポートしてしまった！");
    snprintf(mesg[222], sizeof(mesg[222]), "%s", "毒矢のわな");
    snprintf(mesg[223], sizeof(mesg[223]), "%s", "小さな投げ矢が飛んできて、肩にささった！");
    snprintf(mesg[224], sizeof(mesg[224]), "%s", "催眠ガスのわな");
    snprintf(mesg[225], sizeof(mesg[225]), "%s", "不思議なもやにつつまれ、眠り込んでしまった！");
    snprintf(mesg[226], sizeof(mesg[226]), "%s", "水のわな");
    snprintf(mesg[227], sizeof(mesg[227]), "%s", "頭の上から大量の水が降ってきた！");
    snprintf(mesg[228], sizeof(mesg[228]), "%s", "危うく、わなにはまるところだった。");
    snprintf(mesg[229], sizeof(mesg[229]), "%s", "その方向には、わながない。");
    snprintf(mesg[230], sizeof(mesg[230]), "%s", "不思議な気分におそわれたが、すぐに消えていった。");
    snprintf(mesg[231], sizeof(mesg[231]), "%s", "飲む水薬は？");
    snprintf(mesg[232], sizeof(mesg[232]), "%s", "それは持っていない。");
    snprintf(mesg[233], sizeof(mesg[233]), "%s", "それは水薬ではない。");
    snprintf(mesg[234], sizeof(mesg[234]), "%s", "何だか、力がわいてくるぞ！");
    snprintf(mesg[235], sizeof(mesg[235]), "%s", "これはうまい！ からだがポカポカしてきた。");
    snprintf(mesg[236], sizeof(mesg[236]), "%s", "気分がよくなった！");
    snprintf(mesg[237], sizeof(mesg[237]), "%s", "とても気分がよくなった！");
    snprintf(mesg[238], sizeof(mesg[238]), "%s", "この水薬は毒だった！");
    snprintf(mesg[239], sizeof(mesg[239]), "%s", "ふにゃ？ 何もかもが虹色にみえるなあ？");
    snprintf(mesg[240], sizeof(mesg[240]), "%s", "何だか酔っぱらいみたいな気分だ！");
    snprintf(mesg[241], sizeof(mesg[241]), "%s", "あれ？ ここはどこ？ 私はだれ？");
    snprintf(mesg[242], sizeof(mesg[242]), "%s", "体が宙に浮いてしまった！");
    snprintf(mesg[243], sizeof(mesg[243]), "%s", "体が素早く動くようになった！");
    snprintf(mesg[244], sizeof(mesg[244]), "%s", "う〜む、%sジュースのような味がする。");
    snprintf(mesg[245], sizeof(mesg[245]), "%s", "読む巻き物は？");
    snprintf(mesg[246], sizeof(mesg[246]), "%s", "それは持っていない。");
    snprintf(mesg[247], sizeof(mesg[247]), "%s", "それは巻き物ではない。");
    snprintf(mesg[248], sizeof(mesg[248]), "%s", "遠くから、狂ったような笑い声が聞こえてくる。");
    snprintf(mesg[249], sizeof(mesg[249]), "%s", "手に持った%sが、ほんの少し%s輝きに包まれた。");
    snprintf(mesg[250], sizeof(mesg[250]), "%s", "何だか、手がむずむずする。");
    snprintf(mesg[251], sizeof(mesg[251]), "%s", "着ているよろいが、ほんの少し%s輝きに包まれた。");
    snprintf(mesg[252], sizeof(mesg[252]), "%s", "何だか、体がむずむずする。");
    snprintf(mesg[253], sizeof(mesg[253]), "%s", "これは持ちものを調べる巻き物だった。");
    snprintf(mesg[254], sizeof(mesg[254]), "%s", "知らないうちに眠り込んでしまった。");
    snprintf(mesg[255], sizeof(mesg[255]), "%s", "着ているよろいは、輝く金色の光に守られた。");
    snprintf(mesg[256], sizeof(mesg[256]), "%s", "何だか、顔がむずむずする。");
    snprintf(mesg[257], sizeof(mesg[257]), "%s", "ふっと、誰かに見つめられているような気がした。");
    snprintf(mesg[258], sizeof(mesg[258]), "%s", "ふっと、女神の手に包まれているような気がした。");
    snprintf(mesg[259], sizeof(mesg[259]), "%s", "おや、この巻き物には地図が書いてある！");
    snprintf(mesg[260], sizeof(mesg[260]), "%s", "調べる持ちものは？");
    snprintf(mesg[261], sizeof(mesg[261]), "%s", "それは持っていない。");
    snprintf(mesg[262], sizeof(mesg[262]), "%s", "食べる物は？");
    snprintf(mesg[263], sizeof(mesg[263]), "%s", "それは持っていない。");
    snprintf(mesg[264], sizeof(mesg[264]), "%s", "それは食べられない。");
    snprintf(mesg[265], sizeof(mesg[265]), "%s", "う〜む、まったりとしていて、それでいてこくがある。");
    snprintf(mesg[266], sizeof(mesg[266]), "%s", "ああ、おいしかった。");
    snprintf(mesg[267], sizeof(mesg[267]), "%s", "おや、なんて甘い%sだ。");
    snprintf(mesg[268], sizeof(mesg[268]), "%s", "げげっ、まずい！");
    snprintf(mesg[269], sizeof(mesg[269]), "%s", "急に、体から力が抜けていくような気がした。");
    snprintf(mesg[270], sizeof(mesg[270]), "%s", "怪物は動けなくなった！");
    snprintf(mesg[271], sizeof(mesg[271]), "%s", "怪物どもは動けなくなった！");
    snprintf(mesg[272], sizeof(mesg[272]), "%s", "やっと、あたりの景色が元どおりになった。");
    snprintf(mesg[273], sizeof(mesg[273]), "%s", "暗闇のとばりが上がってゆく。");
    snprintf(mesg[274], sizeof(mesg[274]), "%s", "深い暗闇のとばりがあたりをおおってゆく。");
    snprintf(mesg[275], sizeof(mesg[275]), "%s", "青い");
    snprintf(mesg[276], sizeof(mesg[276]), "%s", "ふたたび、景色が虹色に見えてきた。");
    snprintf(mesg[277], sizeof(mesg[277]), "%s", "ようやく、頭がはっきりしてきた。");
    snprintf(mesg[278], sizeof(mesg[278]), "%s", "振りかざすつえは？");
    snprintf(mesg[279], sizeof(mesg[279]), "%s", "それは持っていない。");
    snprintf(mesg[280], sizeof(mesg[280]), "%s", "それを振りかざすことはできない。");
    snprintf(mesg[281], sizeof(mesg[281]), "%s", "しかし、何も起こらなかった。");
    snprintf(mesg[282], sizeof(mesg[282]), "%s", "しかし、何も起こらなかった。");
    mesg[283][0] = '\0';
    mesg[284][0] = '\0';
    mesg[285][0] = '\0';
    mesg[286][0] = '\0';
    mesg[287][0] = '\0';
    mesg[288][0] = '\0';
    mesg[289][0] = '\0';
    mesg[290][0] = '\0';
    mesg[291][0] = '\0';
    mesg[292][0] = '\0';
    mesg[293][0] = '\0';
    mesg[294][0] = '\0';
    mesg[295][0] = '\0';
    mesg[296][0] = '\0';
    mesg[297][0] = '\0';
    mesg[298][0] = '\0';
    mesg[299][0] = '\0';
    mesg[300][0] = '\0';
    mesg[301][0] = '\0';
    mesg[302][0] = '\0';
    mesg[303][0] = '\0';
    mesg[304][0] = '\0';
    mesg[305][0] = '\0';
    mesg[306][0] = '\0';
    snprintf(mesg[307], sizeof(mesg[307]), "%s", "水ごけの怪物");
    snprintf(mesg[308], sizeof(mesg[308]), "%s", "大こうもり");
    snprintf(mesg[309], sizeof(mesg[309]), "%s", "ケンタウロス");
    snprintf(mesg[310], sizeof(mesg[310]), "%s", "ドラゴン");
    snprintf(mesg[311], sizeof(mesg[311]), "%s", "大うずら");
    snprintf(mesg[312], sizeof(mesg[312]), "%s", "はえとりぐさ");
    snprintf(mesg[313], sizeof(mesg[313]), "%s", "翼ライオン");
    snprintf(mesg[314], sizeof(mesg[314]), "%s", "小鬼");
    snprintf(mesg[315], sizeof(mesg[315]), "%s", "氷の怪物");
    snprintf(mesg[316], sizeof(mesg[316]), "%s", "巨大トカゲ");
    snprintf(mesg[317], sizeof(mesg[317]), "%s", "大はやぶさ");
    snprintf(mesg[318], sizeof(mesg[318]), "%s", "金持ち妖精");
    snprintf(mesg[319], sizeof(mesg[319]), "%s", "メデューサ");
    snprintf(mesg[320], sizeof(mesg[320]), "%s", "ニンフ");
    snprintf(mesg[321], sizeof(mesg[321]), "%s", "欲ばり鬼");
    snprintf(mesg[322], sizeof(mesg[322]), "%s", "幽霊");
    snprintf(mesg[323], sizeof(mesg[323]), "%s", "大つのじか");
    snprintf(mesg[324], sizeof(mesg[324]), "%s", "がらがらへび");
    snprintf(mesg[325], sizeof(mesg[325]), "%s", "へび");
    snprintf(mesg[326], sizeof(mesg[326]), "%s", "巨人");
    snprintf(mesg[327], sizeof(mesg[327]), "%s", "一角獣");
    snprintf(mesg[328], sizeof(mesg[328]), "%s", "バンパイア");
    snprintf(mesg[329], sizeof(mesg[329]), "%s", "死霊");
    snprintf(mesg[330], sizeof(mesg[330]), "%s", "物まねの怪物");
    snprintf(mesg[331], sizeof(mesg[331]), "%s", "雪男");
    snprintf(mesg[332], sizeof(mesg[332]), "%s", "ゾンビ");
    snprintf(mesg[333], sizeof(mesg[333]), "%s", "こけもも");
    snprintf(mesg[334], sizeof(mesg[334]), "%s", "青い");
    snprintf(mesg[335], sizeof(mesg[335]), "%s", "赤い");
    snprintf(mesg[336], sizeof(mesg[336]), "%s", "緑の");
    snprintf(mesg[337], sizeof(mesg[337]), "%s", "灰色の");
    snprintf(mesg[338], sizeof(mesg[338]), "%s", "茶色の");
    snprintf(mesg[339], sizeof(mesg[339]), "%s", "透明な");
    snprintf(mesg[340], sizeof(mesg[340]), "%s", "ピンクの");
    snprintf(mesg[341], sizeof(mesg[341]), "%s", "白い");
    snprintf(mesg[342], sizeof(mesg[342]), "%s", "紫の");
    snprintf(mesg[343], sizeof(mesg[343]), "%s", "黒い");
    snprintf(mesg[344], sizeof(mesg[344]), "%s", "黄色い");
    snprintf(mesg[345], sizeof(mesg[345]), "%s", "水色の");
    snprintf(mesg[346], sizeof(mesg[346]), "%s", "ぶどう色の");
    snprintf(mesg[347], sizeof(mesg[347]), "%s", "オレンジ色の");
    snprintf(mesg[348], sizeof(mesg[348]), "%s", "強さが増す");
    snprintf(mesg[349], sizeof(mesg[349]), "%s", "強さが元にもどる");
    snprintf(mesg[350], sizeof(mesg[350]), "%s", "体力が回復する");
    snprintf(mesg[351], sizeof(mesg[351]), "%s", "体力がとても回復する");
    snprintf(mesg[352], sizeof(mesg[352]), "%s", "毒の");
    snprintf(mesg[353], sizeof(mesg[353]), "%s", "経験が増す");
    snprintf(mesg[354], sizeof(mesg[354]), "%s", "目が見えなくなる");
    snprintf(mesg[355], sizeof(mesg[355]), "%s", "幻覚をおこす");
    snprintf(mesg[356], sizeof(mesg[356]), "%s", "遠くの怪物がわかる");
    snprintf(mesg[357], sizeof(mesg[357]), "%s", "遠くのものがわかる");
    snprintf(mesg[358], sizeof(mesg[358]), "%s", "頭が混乱する");
    snprintf(mesg[359], sizeof(mesg[359]), "%s", "空中に浮きあがる");
    snprintf(mesg[360], sizeof(mesg[360]), "%s", "素早くなる");
    snprintf(mesg[361], sizeof(mesg[361]), "%s", "見えないものが見える");
    snprintf(mesg[362], sizeof(mesg[362]), "%s", "よろいを守る");
    snprintf(mesg[363], sizeof(mesg[363]), "%s", "怪物を封じこめる");
    snprintf(mesg[364], sizeof(mesg[364]), "%s", "武器に魔法をかける");
    snprintf(mesg[365], sizeof(mesg[365]), "%s", "よろいに魔法をかける");
    snprintf(mesg[366], sizeof(mesg[366]), "%s", "持ちものの種類がわかる");
    snprintf(mesg[367], sizeof(mesg[367]), "%s", "テレポートする");
    snprintf(mesg[368], sizeof(mesg[368]), "%s", "眠りにおちる");
    snprintf(mesg[369], sizeof(mesg[369]), "%s", "怪物を近寄せない");
    snprintf(mesg[370], sizeof(mesg[370]), "%s", "のろいを解く");
    snprintf(mesg[371], sizeof(mesg[371]), "%s", "怪物を作りだす");
    snprintf(mesg[372], sizeof(mesg[372]), "%s", "怪物を怒らせる");
    snprintf(mesg[373], sizeof(mesg[373]), "%s", "魔法の地図の");
    snprintf(mesg[374], sizeof(mesg[374]), "%s", "弓");
    snprintf(mesg[375], sizeof(mesg[375]), "%s", "投げ矢");
    snprintf(mesg[376], sizeof(mesg[376]), "%s", "矢");
    snprintf(mesg[377], sizeof(mesg[377]), "%s", "短剣");
    snprintf(mesg[378], sizeof(mesg[378]), "%s", "手裏剣");
    snprintf(mesg[379], sizeof(mesg[379]), "%s", "ほこ");
    snprintf(mesg[380], sizeof(mesg[380]), "%s", "長い剣");
    snprintf(mesg[381], sizeof(mesg[381]), "%s", "大きな剣");
    snprintf(mesg[382], sizeof(mesg[382]), "%s", "革のよろい");
    snprintf(mesg[383], sizeof(mesg[383]), "%s", "かたびら");
    snprintf(mesg[384], sizeof(mesg[384]), "%s", "うろこのよろい");
    snprintf(mesg[385], sizeof(mesg[385]), "%s", "鎖かたびら");
    snprintf(mesg[386], sizeof(mesg[386]), "%s", "帯金のよろい");
    snprintf(mesg[387], sizeof(mesg[387]), "%s", "延金のよろい");
    snprintf(mesg[388], sizeof(mesg[388]), "%s", "鋼鉄のよろい");
    snprintf(mesg[389], sizeof(mesg[389]), "%s", "怪物を遠くに飛ばす");
    snprintf(mesg[390], sizeof(mesg[390]), "%s", "怪物を遅くする");
    snprintf(mesg[391], sizeof(mesg[391]), "%s", "怪物を混乱させる");
    snprintf(mesg[392], sizeof(mesg[392]), "%s", "怪物を見えなくする");
    snprintf(mesg[393], sizeof(mesg[393]), "%s", "ほかの怪物にする");
    snprintf(mesg[394], sizeof(mesg[394]), "%s", "怪物を素早くする");
    snprintf(mesg[395], sizeof(mesg[395]), "%s", "眠らせる");
    snprintf(mesg[396], sizeof(mesg[396]), "%s", "魔法のミサイルの");
    snprintf(mesg[397], sizeof(mesg[397]), "%s", "魔力を封じる");
    snprintf(mesg[398], sizeof(mesg[398]), "%s", "役に立たない");
    snprintf(mesg[399], sizeof(mesg[399]), "%s", "身を隠す");
    snprintf(mesg[400], sizeof(mesg[400]), "%s", "テレポートする");
    snprintf(mesg[401], sizeof(mesg[401]), "%s", "体力が復活する");
    snprintf(mesg[402], sizeof(mesg[402]), "%s", "食べものが長持ちする");
    snprintf(mesg[403], sizeof(mesg[403]), "%s", "強さが増す");
    snprintf(mesg[404], sizeof(mesg[404]), "%s", "強さが減らない");
    snprintf(mesg[405], sizeof(mesg[405]), "%s", "機敏になる");
    snprintf(mesg[406], sizeof(mesg[406]), "%s", "飾りものの");
    snprintf(mesg[407], sizeof(mesg[407]), "%s", "見えないものが見える");
    snprintf(mesg[408], sizeof(mesg[408]), "%s", "よろいが丈夫になる");
    snprintf(mesg[409], sizeof(mesg[409]), "%s", "隠れたものを見つける");
    snprintf(mesg[410], sizeof(mesg[410]), "%s", "鋼鉄");
    snprintf(mesg[411], sizeof(mesg[411]), "%s", "青銅");
    snprintf(mesg[412], sizeof(mesg[412]), "%s", "金");
    snprintf(mesg[413], sizeof(mesg[413]), "%s", "銀");
    snprintf(mesg[414], sizeof(mesg[414]), "%s", "銅");
    snprintf(mesg[415], sizeof(mesg[415]), "%s", "ニッケル");
    snprintf(mesg[416], sizeof(mesg[416]), "%s", "コバルト");
    snprintf(mesg[417], sizeof(mesg[417]), "%s", "すず");
    snprintf(mesg[418], sizeof(mesg[418]), "%s", "鉄");
    snprintf(mesg[419], sizeof(mesg[419]), "%s", "マグネシウム");
    snprintf(mesg[420], sizeof(mesg[420]), "%s", "クロム");
    snprintf(mesg[421], sizeof(mesg[421]), "%s", "石炭");
    snprintf(mesg[422], sizeof(mesg[422]), "%s", "プラチナ");
    snprintf(mesg[423], sizeof(mesg[423]), "%s", "シリコン");
    snprintf(mesg[424], sizeof(mesg[424]), "%s", "チタン");
    snprintf(mesg[425], sizeof(mesg[425]), "%s", "チーク");
    snprintf(mesg[426], sizeof(mesg[426]), "%s", "樫");
    snprintf(mesg[427], sizeof(mesg[427]), "%s", "桜");
    snprintf(mesg[428], sizeof(mesg[428]), "%s", "白樺");
    snprintf(mesg[429], sizeof(mesg[429]), "%s", "松");
    snprintf(mesg[430], sizeof(mesg[430]), "%s", "杉");
    snprintf(mesg[431], sizeof(mesg[431]), "%s", "アメリカ杉");
    snprintf(mesg[432], sizeof(mesg[432]), "%s", "バルサ");
    snprintf(mesg[433], sizeof(mesg[433]), "%s", "象牙やし");
    snprintf(mesg[434], sizeof(mesg[434]), "%s", "胡桃");
    snprintf(mesg[435], sizeof(mesg[435]), "%s", "楓");
    snprintf(mesg[436], sizeof(mesg[436]), "%s", "マホガニー");
    snprintf(mesg[437], sizeof(mesg[437]), "%s", "楡");
    snprintf(mesg[438], sizeof(mesg[438]), "%s", "やし");
    snprintf(mesg[439], sizeof(mesg[439]), "%s", "柿");
    snprintf(mesg[440], sizeof(mesg[440]), "%s", "ダイヤ");
    snprintf(mesg[441], sizeof(mesg[441]), "%s", "アクアマリン");
    snprintf(mesg[442], sizeof(mesg[442]), "%s", "るり");
    snprintf(mesg[443], sizeof(mesg[443]), "%s", "ルビー");
    snprintf(mesg[444], sizeof(mesg[444]), "%s", "エメラルド");
    snprintf(mesg[445], sizeof(mesg[445]), "%s", "サファイア");
    snprintf(mesg[446], sizeof(mesg[446]), "%s", "紫水晶");
    snprintf(mesg[447], sizeof(mesg[447]), "%s", "水晶");
    snprintf(mesg[448], sizeof(mesg[448]), "%s", "虎目石");
    snprintf(mesg[449], sizeof(mesg[449]), "%s", "オパール");
    snprintf(mesg[450], sizeof(mesg[450]), "%s", "めのう");
    snprintf(mesg[451], sizeof(mesg[451]), "%s", "トルコ石");
    snprintf(mesg[452], sizeof(mesg[452]), "%s", "真珠");
    snprintf(mesg[453], sizeof(mesg[453]), "%s", "ざくろ石");
    snprintf(mesg[454], sizeof(mesg[454]), "%s", "ぶん ");
    snprintf(mesg[455], sizeof(mesg[455]), "%s", "に ");
    snprintf(mesg[456], sizeof(mesg[456]), "%s", "とす ");
    snprintf(mesg[457], sizeof(mesg[457]), "%s", "ら ");
    snprintf(mesg[458], sizeof(mesg[458]), "%s", "ぽみ ");
    snprintf(mesg[459], sizeof(mesg[459]), "%s", "ぷ ");
    snprintf(mesg[460], sizeof(mesg[460]), "%s", "どん ");
    snprintf(mesg[461], sizeof(mesg[461]), "%s", "せろ ");
    snprintf(mesg[462], sizeof(mesg[462]), "%s", "い ");
    snprintf(mesg[463], sizeof(mesg[463]), "%s", "か ");
    snprintf(mesg[464], sizeof(mesg[464]), "%s", "そろ ");
    snprintf(mesg[465], sizeof(mesg[465]), "%s", "む ");
    snprintf(mesg[466], sizeof(mesg[466]), "%s", "ろお ");
    snprintf(mesg[467], sizeof(mesg[467]), "%s", "わ ");
    snprintf(mesg[468], sizeof(mesg[468]), "%s", "おふ ");
    snprintf(mesg[469], sizeof(mesg[469]), "%s", "ろん ");
    snprintf(mesg[470], sizeof(mesg[470]), "%s", "わっと ");
    snprintf(mesg[471], sizeof(mesg[471]), "%s", "ぴお ");
    snprintf(mesg[472], sizeof(mesg[472]), "%s", "ぽんぽ ");
    snprintf(mesg[473], sizeof(mesg[473]), "%s", "どどら ");
    snprintf(mesg[474], sizeof(mesg[474]), "%s", "ひゅ ");
    snprintf(mesg[475], sizeof(mesg[475]), "%s", "よふ ");
    snprintf(mesg[476], sizeof(mesg[476]), "%s", "ぽた ");
    snprintf(mesg[477], sizeof(mesg[477]), "%s", "るん ");
    snprintf(mesg[478], sizeof(mesg[478]), "%s", "ばび ");
    snprintf(mesg[479], sizeof(mesg[479]), "%s", "ろろり ");
    snprintf(mesg[480], sizeof(mesg[480]), "%s", "ずず ");
    snprintf(mesg[481], sizeof(mesg[481]), "%s", "ぐり ");
    snprintf(mesg[482], sizeof(mesg[482]), "%s", "こも ");
    snprintf(mesg[483], sizeof(mesg[483]), "%s", "きき ");
    snprintf(mesg[484], sizeof(mesg[484]), "%s", "およ ");
    snprintf(mesg[485], sizeof(mesg[485]), "%s", "いむ ");
    snprintf(mesg[486], sizeof(mesg[486]), "%s", "にゃあ ");
    snprintf(mesg[487], sizeof(mesg[487]), "%s", "うー ");
    snprintf(mesg[488], sizeof(mesg[488]), "%s", "ぐふる ");
    snprintf(mesg[489], sizeof(mesg[489]), "%s", "こぴ ");
    snprintf(mesg[490], sizeof(mesg[490]), "%s", "すーる ");
    snprintf(mesg[491], sizeof(mesg[491]), "%s", "ぽろん ");
    snprintf(mesg[492], sizeof(mesg[492]), "%s", "みーる ");
    snprintf(mesg[493], sizeof(mesg[493]), "%s", "ぽきし ");
    mesg[494][0] = '\0';
    mesg[495][0] = '\0';
    mesg[496][0] = '\0';
    mesg[497][0] = '\0';
    mesg[498][0] = '\0';
    mesg[499][0] = '\0';
    mesg[500][0] = '\0';
    mesg[501][0] = '\0';
    mesg[502][0] = '\0';
    mesg[503][0] = '\0';
    mesg[504][0] = '\0';
    mesg[505][0] = '\0';
    mesg[506][0] = '\0';
}

#endif /* MESG_J_H */
